# Generated by Django 4.2.5 on 2023-10-05 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MeuApp", "0010_alter_ride_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="free_seats",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="ride",
            name="passengers",
            field=models.ManyToManyField(
                blank=True,
                related_name="rides_as_passenger",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
