# Generated by Django 4.2.5 on 2023-10-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MeuApp", "0011_alter_ride_driver_alter_ride_free_seats_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
